/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'title' : string,
  'youtube_url' : string,
  'difficulty' : DifficultyLevel,
  'description' : string,
  'thumbnail_url' : string,
  'category' : string,
}
export interface CourseProgress { 'completedAt' : Time, 'courseId' : string }
export type DifficultyLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface JobApplication {
  'id' : string,
  'principal' : Principal,
  'name' : string,
  'jobId' : string,
  'coverLetter' : string,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface JobListing {
  'id' : string,
  'title' : string,
  'apply_url' : string,
  'time' : Time,
  'description' : string,
  'company' : string,
  'location' : string,
  'job_type' : JobType,
}
export type JobType = { 'internship' : null } |
  { 'part_time' : null } |
  { 'full_time' : null };
export interface MCQQuestion {
  'id' : string,
  'question_text' : string,
  'topic_id' : string,
  'correct_option_index' : bigint,
  'options' : Array<string>,
}
export interface QuizAttempt {
  'score' : bigint,
  'timestamp' : Time,
  'topicId' : string,
}
export interface ResumeProfile {
  'name' : string,
  'education' : Array<
    { 'institution' : string, 'year' : bigint, 'degree' : string }
  >,
  'email' : string,
  'experience' : Array<
    {
      'duration' : string,
      'role' : string,
      'description' : string,
      'company' : string,
    }
  >,
  'summary' : string,
  'phone' : string,
  'skills' : Array<string>,
}
export interface StudentAccount {
  'name' : string,
  'securityQuestion' : string,
  'email' : string,
  'passwordHash' : string,
  'securityAnswerHash' : string,
  'registeredAt' : Time,
}
export interface TestTopic {
  'id' : string,
  'title' : string,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[string, string, string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, string, string, string, DifficultyLevel],
    string
  >,
  'createJobListing' : ActorMethod<
    [string, string, string, string, string, JobType],
    string
  >,
  'createQuestion' : ActorMethod<
    [string, string, Array<string>, bigint],
    string
  >,
  'createTestTopic' : ActorMethod<[string, string], string>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteJobListing' : ActorMethod<[string], undefined>,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteTestTopic' : ActorMethod<[string], undefined>,
  'getAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getAllQuestions' : ActorMethod<[], Array<MCQQuestion>>,
  'getAllStudents' : ActorMethod<[], Array<StudentAccount>>,
  'getAllTestTopics' : ActorMethod<[], Array<TestTopic>>,
  'getApplicationsByJob' : ActorMethod<[string], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getJobListing' : ActorMethod<[string], [] | [JobListing]>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getQuestion' : ActorMethod<[string], [] | [MCQQuestion]>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<MCQQuestion>>,
  'getSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getStudentCount' : ActorMethod<[], bigint>,
  'getTestTopic' : ActorMethod<[string], [] | [TestTopic]>,
  'getUserCourseProgress' : ActorMethod<[Principal], Array<CourseProgress>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizAttempts' : ActorMethod<[Principal], Array<QuizAttempt>>,
  'getUserXP' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginStudent' : ActorMethod<[string, string], [] | [StudentAccount]>,
  'recordCourseCompletion' : ActorMethod<[string], undefined>,
  'recordQuizAttempt' : ActorMethod<[string, bigint], undefined>,
  'registerStudent' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'emailTaken' : null } |
      { 'invalidInput' : null }
  >,
  'resetPasswordWithSecurityAnswer' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'rateLimited' : null } |
      { 'wrongAnswer' : null }
  >,
  'resumeProfile' : ActorMethod<[Principal], [] | [ResumeProfile]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveResumeProfile' : ActorMethod<[ResumeProfile], undefined>,
  'updateCourse' : ActorMethod<
    [string, string, string, string, string, string, DifficultyLevel],
    undefined
  >,
  'updateJobListing' : ActorMethod<
    [string, string, string, string, string, string, JobType],
    undefined
  >,
  'updateQuestion' : ActorMethod<
    [string, string, string, Array<string>, bigint],
    undefined
  >,
  'updateTestTopic' : ActorMethod<[string, string, string], undefined>,
  'updateXP' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];