/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DifficultyLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const JobType = IDL.Variant({
  'internship' : IDL.Null,
  'part_time' : IDL.Null,
  'full_time' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'youtube_url' : IDL.Text,
  'difficulty' : DifficultyLevel,
  'description' : IDL.Text,
  'thumbnail_url' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const JobListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'apply_url' : IDL.Text,
  'time' : Time,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
  'job_type' : JobType,
});
export const MCQQuestion = IDL.Record({
  'id' : IDL.Text,
  'question_text' : IDL.Text,
  'topic_id' : IDL.Text,
  'correct_option_index' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const TestTopic = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CourseProgress = IDL.Record({
  'completedAt' : Time,
  'courseId' : IDL.Text,
});
export const QuizAttempt = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Time,
  'topicId' : IDL.Text,
});
export const ResumeProfile = IDL.Record({
  'name' : IDL.Text,
  'education' : IDL.Vec(
    IDL.Record({
      'institution' : IDL.Text,
      'year' : IDL.Nat,
      'degree' : IDL.Text,
    })
  ),
  'email' : IDL.Text,
  'experience' : IDL.Vec(
    IDL.Record({
      'duration' : IDL.Text,
      'role' : IDL.Text,
      'description' : IDL.Text,
      'company' : IDL.Text,
    })
  ),
  'summary' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, DifficultyLevel],
      [IDL.Text],
      [],
    ),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
      [IDL.Text],
      [],
    ),
  'createQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createTestTopic' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteJobListing' : IDL.Func([IDL.Text], [], []),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'deleteTestTopic' : IDL.Func([IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(MCQQuestion)], ['query']),
  'getAllTestTopics' : IDL.Func([], [IDL.Vec(TestTopic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getJobListing' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
  'getQuestion' : IDL.Func([IDL.Text], [IDL.Opt(MCQQuestion)], ['query']),
  'getQuestionsByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MCQQuestion)],
      ['query'],
    ),
  'getTestTopic' : IDL.Func([IDL.Text], [IDL.Opt(TestTopic)], ['query']),
  'getUserCourseProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CourseProgress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getUserXP' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCourseCompletion' : IDL.Func([IDL.Text], [], []),
  'recordQuizAttempt' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'resumeProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ResumeProfile)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveResumeProfile' : IDL.Func([ResumeProfile], [], []),
  'updateCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        DifficultyLevel,
      ],
      [],
      [],
    ),
  'updateJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
      [],
      [],
    ),
  'updateQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'updateTestTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateXP' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DifficultyLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'internship' : IDL.Null,
    'part_time' : IDL.Null,
    'full_time' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'youtube_url' : IDL.Text,
    'difficulty' : DifficultyLevel,
    'description' : IDL.Text,
    'thumbnail_url' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const JobListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'apply_url' : IDL.Text,
    'time' : Time,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
    'job_type' : JobType,
  });
  const MCQQuestion = IDL.Record({
    'id' : IDL.Text,
    'question_text' : IDL.Text,
    'topic_id' : IDL.Text,
    'correct_option_index' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const TestTopic = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CourseProgress = IDL.Record({
    'completedAt' : Time,
    'courseId' : IDL.Text,
  });
  const QuizAttempt = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Time,
    'topicId' : IDL.Text,
  });
  const ResumeProfile = IDL.Record({
    'name' : IDL.Text,
    'education' : IDL.Vec(
      IDL.Record({
        'institution' : IDL.Text,
        'year' : IDL.Nat,
        'degree' : IDL.Text,
      })
    ),
    'email' : IDL.Text,
    'experience' : IDL.Vec(
      IDL.Record({
        'duration' : IDL.Text,
        'role' : IDL.Text,
        'description' : IDL.Text,
        'company' : IDL.Text,
      })
    ),
    'summary' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, DifficultyLevel],
        [IDL.Text],
        [],
      ),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
        [IDL.Text],
        [],
      ),
    'createQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createTestTopic' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteJobListing' : IDL.Func([IDL.Text], [], []),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'deleteTestTopic' : IDL.Func([IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(MCQQuestion)], ['query']),
    'getAllTestTopics' : IDL.Func([], [IDL.Vec(TestTopic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getJobListing' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
    'getQuestion' : IDL.Func([IDL.Text], [IDL.Opt(MCQQuestion)], ['query']),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MCQQuestion)],
        ['query'],
      ),
    'getTestTopic' : IDL.Func([IDL.Text], [IDL.Opt(TestTopic)], ['query']),
    'getUserCourseProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CourseProgress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getUserXP' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCourseCompletion' : IDL.Func([IDL.Text], [], []),
    'recordQuizAttempt' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'resumeProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ResumeProfile)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveResumeProfile' : IDL.Func([ResumeProfile], [], []),
    'updateCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          DifficultyLevel,
        ],
        [],
        [],
      ),
    'updateJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
        [],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'updateTestTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateXP' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };