/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface MCQQuestion {
    id: string;
    question_text: string;
    topic_id: string;
    correct_option_index: bigint;
    options: Array<string>;
}
export interface JobApplication {
    id: string;
    principal: Principal;
    name: string;
    jobId: string;
    coverLetter: string;
    email: string;
    timestamp: Time;
    phone: string;
}
export interface JobListing {
    id: string;
    title: string;
    apply_url: string;
    time: Time;
    description: string;
    company: string;
    location: string;
    job_type: JobType;
}
export interface Course {
    id: string;
    title: string;
    youtube_url: string;
    difficulty: DifficultyLevel;
    description: string;
    thumbnail_url: string;
    category: string;
}
export interface StudentAccount {
    name: string;
    securityQuestion: string;
    email: string;
    passwordHash: string;
    securityAnswerHash: string;
    registeredAt: Time;
}
export interface QuizAttempt {
    score: bigint;
    timestamp: Time;
    topicId: string;
}
export interface TestTopic {
    id: string;
    title: string;
    description: string;
}
export interface ResumeProfile {
    name: string;
    education: Array<{
        institution: string;
        year: bigint;
        degree: string;
    }>;
    email: string;
    experience: Array<{
        duration: string;
        role: string;
        description: string;
        company: string;
    }>;
    summary: string;
    phone: string;
    skills: Array<string>;
}
export interface CourseProgress {
    completedAt: Time;
    courseId: string;
}
export interface UserProfile {
    name: string;
}
export enum DifficultyLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum JobType {
    internship = "internship",
    part_time = "part_time",
    full_time = "full_time"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ok_emailTaken_invalidInput {
    ok = "ok",
    emailTaken = "emailTaken",
    invalidInput = "invalidInput"
}
export enum Variant_ok_notFound_rateLimited_wrongAnswer {
    ok = "ok",
    notFound = "notFound",
    rateLimited = "rateLimited",
    wrongAnswer = "wrongAnswer"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyForJob(jobId: string, name: string, email: string, phone: string, coverLetter: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(title: string, description: string, category: string, youtube_url: string, thumbnail_url: string, difficulty: DifficultyLevel): Promise<string>;
    createJobListing(title: string, company: string, location: string, description: string, apply_url: string, job_type: JobType): Promise<string>;
    createQuestion(topicId: string, question_text: string, options: Array<string>, correct_option_index: bigint): Promise<string>;
    createTestTopic(title: string, description: string): Promise<string>;
    deleteCourse(id: string): Promise<void>;
    deleteJobListing(id: string): Promise<void>;
    deleteQuestion(id: string): Promise<void>;
    deleteStudent(email: string): Promise<void>;
    deleteTestTopic(id: string): Promise<void>;
    getAllApplications(): Promise<Array<JobApplication>>;
    getAllCourses(): Promise<Array<Course>>;
    getAllJobListings(): Promise<Array<JobListing>>;
    getAllQuestions(): Promise<Array<MCQQuestion>>;
    getAllStudents(): Promise<Array<StudentAccount>>;
    getAllTestTopics(): Promise<Array<TestTopic>>;
    getApplicationsByJob(jobId: string): Promise<Array<JobApplication>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(id: string): Promise<Course | null>;
    getJobListing(id: string): Promise<JobListing | null>;
    getMyApplications(): Promise<Array<JobApplication>>;
    getQuestion(id: string): Promise<MCQQuestion | null>;
    getQuestionsByTopic(topicId: string): Promise<Array<MCQQuestion>>;
    getSecurityQuestion(email: string): Promise<string | null>;
    getStudentCount(): Promise<bigint>;
    getTestTopic(id: string): Promise<TestTopic | null>;
    getUserCourseProgress(user: Principal): Promise<Array<CourseProgress>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserQuizAttempts(user: Principal): Promise<Array<QuizAttempt>>;
    getUserXP(user: Principal): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    loginStudent(email: string, passwordHash: string): Promise<StudentAccount | null>;
    recordCourseCompletion(courseId: string): Promise<void>;
    recordQuizAttempt(topicId: string, score: bigint): Promise<void>;
    registerStudent(name: string, email: string, passwordHash: string, securityQuestion: string, securityAnswerHash: string): Promise<Variant_ok_emailTaken_invalidInput>;
    resetPasswordWithSecurityAnswer(email: string, securityAnswerHash: string, newPasswordHash: string): Promise<Variant_ok_notFound_rateLimited_wrongAnswer>;
    resumeProfile(user: Principal): Promise<ResumeProfile | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveResumeProfile(profile: ResumeProfile): Promise<void>;
    updateCourse(id: string, title: string, description: string, category: string, youtube_url: string, thumbnail_url: string, difficulty: DifficultyLevel): Promise<void>;
    updateJobListing(id: string, title: string, company: string, location: string, description: string, apply_url: string, job_type: JobType): Promise<void>;
    updateQuestion(id: string, topicId: string, question_text: string, options: Array<string>, correct_option_index: bigint): Promise<void>;
    updateTestTopic(id: string, title: string, description: string): Promise<void>;
    updateXP(xp: bigint): Promise<void>;
}
import type { Course as _Course, DifficultyLevel as _DifficultyLevel, JobListing as _JobListing, JobType as _JobType, MCQQuestion as _MCQQuestion, ResumeProfile as _ResumeProfile, StudentAccount as _StudentAccount, TestTopic as _TestTopic, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyForJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: DifficultyLevel): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4, to_candid_DifficultyLevel_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4, to_candid_DifficultyLevel_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createJobListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: JobType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createQuestion(arg0: string, arg1: string, arg2: Array<string>, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTestTopic(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestTopic(arg0, arg1);
            return result;
        }
    }
    async deleteCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteJobListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobListing(arg0);
            return result;
        }
    }
    async deleteQuestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTestTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestTopic(arg0);
            return result;
        }
    }
    async getAllApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobListings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobListings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuestions(): Promise<Array<MCQQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<StudentAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllTestTopics(): Promise<Array<TestTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestTopics();
            return result;
        }
    }
    async getApplicationsByJob(arg0: string): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsByJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsByJob(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: string): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListing(arg0: string): Promise<JobListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListing(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListing(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return result;
        }
    }
    async getQuestion(arg0: string): Promise<MCQQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByTopic(arg0: string): Promise<Array<MCQQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByTopic(arg0);
            return result;
        }
    }
    async getSecurityQuestion(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityQuestion(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityQuestion(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCount();
            return result;
        }
    }
    async getTestTopic(arg0: string): Promise<TestTopic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestTopic(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestTopic(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCourseProgress(arg0: Principal): Promise<Array<CourseProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCourseProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCourseProgress(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserQuizAttempts(arg0: Principal): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserQuizAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserQuizAttempts(arg0);
            return result;
        }
    }
    async getUserXP(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserXP(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginStudent(arg0: string, arg1: string): Promise<StudentAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStudent(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStudent(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordCourseCompletion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCourseCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCourseCompletion(arg0);
            return result;
        }
    }
    async recordQuizAttempt(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordQuizAttempt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordQuizAttempt(arg0, arg1);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Variant_ok_emailTaken_invalidInput> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordWithSecurityAnswer(arg0: string, arg1: string, arg2: string): Promise<Variant_ok_notFound_rateLimited_wrongAnswer> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithSecurityAnswer(arg0, arg1, arg2);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithSecurityAnswer(arg0, arg1, arg2);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async resumeProfile(arg0: Principal): Promise<ResumeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveResumeProfile(arg0: ResumeProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResumeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResumeProfile(arg0);
            return result;
        }
    }
    async updateCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: DifficultyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateJobListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: JobType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateQuestion(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTestTopic(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestTopic(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestTopic(arg0, arg1, arg2);
            return result;
        }
    }
    async updateXP(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateXP(arg0);
            return result;
        }
    }
}
function from_candid_Course_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobListing_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobListing]): JobListing | null {
    return value.length === 0 ? null : from_candid_JobListing_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MCQQuestion]): MCQQuestion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestTopic]): TestTopic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentAccount]): StudentAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeProfile]): ResumeProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    apply_url: string;
    time: _Time;
    description: string;
    company: string;
    location: string;
    job_type: _JobType;
}): {
    id: string;
    title: string;
    apply_url: string;
    time: Time;
    description: string;
    company: string;
    location: string;
    job_type: JobType;
} {
    return {
        id: value.id,
        title: value.title,
        apply_url: value.apply_url,
        time: value.time,
        description: value.description,
        company: value.company,
        location: value.location,
        job_type: from_candid_JobType_n15(_uploadFile, _downloadFile, value.job_type)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    youtube_url: string;
    difficulty: _DifficultyLevel;
    description: string;
    thumbnail_url: string;
    category: string;
}): {
    id: string;
    title: string;
    youtube_url: string;
    difficulty: DifficultyLevel;
    description: string;
    thumbnail_url: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        youtube_url: value.youtube_url,
        difficulty: from_candid_DifficultyLevel_n10(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        thumbnail_url: value.thumbnail_url,
        category: value.category
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): DifficultyLevel {
    return "intermediate" in value ? DifficultyLevel.intermediate : "beginner" in value ? DifficultyLevel.beginner : "advanced" in value ? DifficultyLevel.advanced : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internship: null;
} | {
    part_time: null;
} | {
    full_time: null;
}): JobType {
    return "internship" in value ? JobType.internship : "part_time" in value ? JobType.part_time : "full_time" in value ? JobType.full_time : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    emailTaken: null;
} | {
    invalidInput: null;
}): Variant_ok_emailTaken_invalidInput {
    return "ok" in value ? Variant_ok_emailTaken_invalidInput.ok : "emailTaken" in value ? Variant_ok_emailTaken_invalidInput.emailTaken : "invalidInput" in value ? Variant_ok_emailTaken_invalidInput.invalidInput : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    rateLimited: null;
} | {
    wrongAnswer: null;
}): Variant_ok_notFound_rateLimited_wrongAnswer {
    return "ok" in value ? Variant_ok_notFound_rateLimited_wrongAnswer.ok : "notFound" in value ? Variant_ok_notFound_rateLimited_wrongAnswer.notFound : "rateLimited" in value ? Variant_ok_notFound_rateLimited_wrongAnswer.rateLimited : "wrongAnswer" in value ? Variant_ok_notFound_rateLimited_wrongAnswer.wrongAnswer : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == DifficultyLevel.intermediate ? {
        intermediate: null
    } : value == DifficultyLevel.beginner ? {
        beginner: null
    } : value == DifficultyLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    internship: null;
} | {
    part_time: null;
} | {
    full_time: null;
} {
    return value == JobType.internship ? {
        internship: null
    } : value == JobType.part_time ? {
        part_time: null
    } : value == JobType.full_time ? {
        full_time: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
